# Generated by Django 4.2.6 on 2023-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telesettings',
            name='type_price',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='gold', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
