# Generated by Django 4.2.6 on 2023-12-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_telesettings_type_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telesettings',
            name='type_price',
        ),
    ]
