# Generated by Django 4.2.6 on 2023-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_remove_telesettings_type_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('order_phone', models.CharField(max_length=20, verbose_name='Телефон заказчика')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='telesettings',
            name='type_price',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='gold', max_length=10, unique=True, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_chat',
            field=models.CharField(max_length=255, verbose_name='Чат айди'),
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_token',
            field=models.CharField(max_length=255, verbose_name='Токен'),
        ),
    ]
