# Generated by Django 4.2.6 on 2023-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0004_order_telesettings_type_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_chat',
            field=models.CharField(max_length=200, verbose_name='Чат айди'),
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_token',
            field=models.CharField(max_length=200, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='type_price',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип цены'),
        ),
    ]
