# Generated by Django 4.2.6 on 2023-12-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0005_delete_order_alter_telesettings_tg_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telesettings',
            name='type_price',
        ),
    ]
